{% set name = "mycli" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 935507a44a2ccd3854be82f8879f6f199ef56c0c76e95274893fd8b95424fcb9

build:
  number: 0
  entry_points:
    - mycli = mycli.main:cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - click >=7.0
    - pygments >=1.6
    - prompt_toolkit >=3.0.6,<4.0.0
    - pymysql >=0.9.2
    - sqlparse >=0.3.0,<0.4.0
    - configobj >=5.0.5
    - cryptography >=1.0.0
    - cli_helpers >=2.0.1
    - pyperclip >=1.8.1
    - python
    - tabulate

test:
  imports:
    - mycli
    - mycli.packages
    - mycli.packages.special
    - mycli.packages.tabular_output
  commands:
    - mycli --help

about:
  home: https://mycli.net
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: CLI for MySQL Database. With auto-completion and syntax highlighting.
  doc_url: https://www.mycli.net/docs
  dev_url: https://github.com/dbcli/mycli

extra:
  recipe-maintainers:
    - tschoonj
