{% set name = "mycli" %}
{% set version = "1.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66bfac0be21df16e01ff6187cc9cece6676a4c5f1bd3435887e633b5e380e4c3

build:
  number: 0
  entry_points:
    - mycli = mycli.main:cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python 3.7
    - setuptools
  run:
    - click >=7.0
    - cryptography >=1.0.0
    - pygments >=1.6
    - prompt_toolkit >=3.0.6,<4.0.0
    - pymysql >=0.9.2
    - sqlparse >=0.3.0,<0.5.0
    - sqlglot >=5.1.3
    - configobj >=5.0.5
    - cli_helpers >=2.2.1
    - pyaes >=1.6.1
    - pyperclip >=1.8.1
    - pyfzf >=0.3.1
    - python >=3.7
    - importlib-resources >=5.0.0

test:
  imports:
    - mycli
    - mycli.packages
    - mycli.packages.special
    - mycli.packages.tabular_output
  commands:
    - mycli --help

about:
  home: https://mycli.net
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: CLI for MySQL Database. With auto-completion and syntax highlighting.
  doc_url: https://www.mycli.net/docs
  dev_url: https://github.com/dbcli/mycli

extra:
  recipe-maintainers:
    - tschoonj
