{% set name = "mycli" %}
{% set version = "1.24.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5eb3e1a3e6cf8f2ce3d9de96e0a4783f4f53d7f15792b42f8463e8b60a28201e

build:
  number: 0
  entry_points:
    - mycli = mycli.main:cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - click >=7.0
    - cryptography >=1.0.0
    - pygments >=1.6
    - prompt_toolkit >=3.0.6,<4.0.0
    - pymysql >=0.9.2
    - sqlparse >=0.3.0,<0.4.0
    - configobj >=5.0.5
    - cli_helpers >=2.0.1
    - pyaes >=1.6.1
    - pyperclip >=1.8.1
    - python
    - tabulate
    - importlib_resources >=5.0.0  # [py < 39]

test:
  imports:
    - mycli
    - mycli.packages
    - mycli.packages.special
    - mycli.packages.tabular_output
  commands:
    - mycli --help

about:
  home: https://mycli.net
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: CLI for MySQL Database. With auto-completion and syntax highlighting.
  doc_url: https://www.mycli.net/docs
  dev_url: https://github.com/dbcli/mycli

extra:
  recipe-maintainers:
    - tschoonj
