travis:
  secure:
    BINSTAR_TOKEN: SMITnhRruZuWckeyNA7pKCo3DDa9xZjRczFAkRiUQndhkqd6mu5MBVuQ8Lzfkzya7wO+MK4Uuj4tGQkZmlbC1l4APhuEgGQ3rm8eqEjtViTVXbwS993dmVWTxsrZSFd3qkkb1fd6nR8XZnB0VmoX83Kyjn44ni0SlhUPTMjo6FK3xiyCIJAjbBfkZlahtGt5lfSW5CgN0FDOW2BqdLGa/3bcdSCUrrdnrBw+xr4zdNi5WVJM0tASX+sp2TT19L4Ys0xFKQYup7tW+iR8FsVhffk6Gl/2lnfFFcz/9XAFoIQfZPJoXOX6hGUzqMaeY418cDMFo6munqwhTWbZFF+NvfvaAQwYP62Xia0gkGal2O54sxAH0lrsYdBBKPRGT9yPfQyZehhDfvJluafP3KIk4Vc3W63MmlXCFK67Xbqyn5eN8ur/y3ZfcEwVGHkOGA1KYxUIBRQnt3neIAe15DU8Yos8xeEFeDOBHZakEHIILjBJBqczIOJQB/cmzom5Z0r9XfkpVzaCe1Ld60+DWuGCjBmVitjzywjfL4zyM+f/XRYuXHyjEbtN3/rNxZ9IXtGj8iZV8dq2tzGBeDdEe+V5PzcD4kQ4LwvxEpDwkqBFNuLZBJhGD6ge250z7W5+1jZqHEuSC1Vyn9ZifwpJ6Qwq/+4VIUacc1aigYC00yAoaFg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
